### ISSUE TITLE
Question for Git

### ISSUE THREAD

**Issue by Ran-Vera-Wei** [DS-XL/ds-intro-class-2022#4]
Hi Emma,

I actually faced a problem with using the git command. When I tried to add a code file, it always raises a warning: 

 - 'in the working copy of 'HW1.ipynb', LF will be replaced by CRLF the next time Git touches it'

What might happen here?

Thanks,
Ran

**Comment by emma-oc** [comment]
Interesting warning, not sure if it's related to Window/Mac env difference, but here are sone posts that might be helpful:
- https://stackoverflow.com/questions/1598260/make-git-lf-will-be-replaced-by-crlf-warnings-go-away 
- https://stackoverflow.com/questions/17628305/windows-git-warning-lf-will-be-replaced-by-crlf-is-that-warning-tail-backwar/72332319#72332319

**Comment by Ran-Vera-Wei** [comment]
I applied solutions in the first link and solved this problem, thanks!
